### ISSUE TITLE
Token and Refresh Token management

### ISSUE THREAD

**Issue by JSeam2** [PedroBern/django-graphql-auth#1]
Hi, thanks for adding me as a collaborator in the project. 

I understand that django-graphql-jwt is used in the backend as a way of handling authentication. Currently, I believe the library has issues handling refreshToken as a cookie. At the moment, in order to use refreshToken you will have to store it somewhere within the browser's  session storage, this is vulnerable to XSS. A better option is to store the token as a httpOnly token. While this is still vulnerable to CSRF attacks, I believe Django does a good job at managing CSRF vulnerabilities.

The next issue with the library is that calling refreshToken generates a new refreshToken even if the token is not about to expire. This is wasteful and will quickly pollute the database with unnecessary data.

I believe the django-graphql-jwt library is not really ready for production usage. I have been trying to work on these problems in my fork. The maintainer of django-graphql-jwt is not really responsive. If you have any ideas to address this problem it would be fantastic.

**Comment by PedroBern** [comment]
Thanks for accepting the invitation! I saw you [here](https://github.com/flavors/django-graphql-jwt/issues/163).

> ... calling refreshToken generates a new refreshToken even if the token is not about to expire.

The [token_auth](https://github.com/flavors/django-graphql-jwt/blob/6e816445b72e7582d0595fda9e7e5d0486026045/graphql_jwt/decorators.py#L65) calls refresh_token_lazy, which calls [create_refresh_token](https://github.com/flavors/django-graphql-jwt/blob/6e816445b72e7582d0595fda9e7e5d0486026045/graphql_jwt/refresh_token/shortcuts.py#L23).

The solution could be something like:

```python
# graphql_jwt.refresh_token.shortcuts.py 

# from
def create_refresh_token(user):
    return get_refresh_token_model().objects.create(user=user)

refresh_token_lazy = lazy(lambda u: create_refresh_token(u).get_token(), str)

# to
def get_or_create_refresh_token(user):
    # pseudo code:
    # if there is a refresh token, not expired for that user,
    #    return that refresh token
    return get_refresh_token_model().objects.create(user=user)

refresh_token_lazy = lazy(lambda u: get_or_create_refresh_token(u).get_token(), str)
```

**Comment by PedroBern** [comment]
Closing this, as it is specific django-graphql-jwt issue.
