### ISSUE TITLE
Async email support

### ISSUE THREAD

**Issue by PedroBern** [PedroBern/django-graphql-auth#11]
Currently, all emails are sent in the `mixins.py` but would be great to have async support.

I think the easiest way to make an optional plug and play support would be creating a new setting to enter a function that wraps each send email call.

**Actually it's not an async email support, but make easy to integrate with your own async solution.**

```python
# settings
EMAIL_ASYNC_TASK = None
```

 Then it accepts a function path"

```python
EMAIL_ASYNC_TASK: "path/to/task"
```

The task need to accept the email send function and its arguments, usage with celery would be something like this:

```python
from celery import task
 
@task
def graphql_auth_async_email(func, *args):
    """
    Task to send an e-mail for the graphql_auth package
    """
 
    return func(*args)
```

Then, in the `mixins.py`, we need to change all send email calls, for example:

```python
# from
user.status.send_activation_email(info)

# to
if app_settings.EMAIL_ASYNC_TASK:
    app_settings.EMAIL_ASYNC_TASK(user.status.send_activation_email, info)
else:
    user.status.send_activation_email(info)
```

Of course, to make this work we must import the function from its path in the `settings.py`, probably using:

```python
from django.utils.module_loading import import_string
```

**Comment by yanivtoledano** [comment]
I see this has been mentioned [here](https://github.com/PedroBern/django-graphql-auth/projects/3#card-34004517). Was not aware this is easily achievable with the current setup however?

**Comment by PedroBern** [comment]
> Was not aware this is easily achievable with the current setup however?

You can use your favorite email provider, just follow the [anymail 1-2-3](https://github.com/anymail/django-anymail#anymail-1-2-3).

> At the moment, I believe emails in general are only customizable via templates

Yes currently the email templates are customizable only by django templates,  it can be enhanced in the future, or you can propose changes and make a pull request :D

**Comment by nazmulhasan85** [comment]
It's a great idea! I want to add something more here.

Is it possible to bring some hook-able option so that User can handle email sending part by themselves?

For example, I've all the email template in mandrill. So I just wanted to reuse all those templates with the arguments.

**Comment by PedroBern** [comment]
> Is it possible to bring some hook-able option so that User can handle email sending part by themselves?

@nazmulhasan85 Yes, you can do that! The easiest way right now is to simply:
- add a hook inside de [UserStatus.send](https://github.com/PedroBern/django-graphql-auth/blob/master/graphql_auth/models.py#L40);
- take the `self`, `context`, `template`, `_subject`, `message`, `html_message` as arguments. Although you'd probably build the last 2 or 3 with the context, it would be better to support it.
- Return the hook before the `return` line in case a hook function is specified in the settings;
- Create a setting for this that takes one function path (just like [here](https://github.com/PedroBern/django-graphql-auth/issues/11#issue-575675915))to handle all email sending (and in the function the user would need to distinguish the email type using the `template` argument);
- Update the docs, settings part, and warn that this custom function should raise the same possible exceptions as `django.core.mail.send_email` in order to work.

Suggestions? What you think?

Also, it would be useful to solve #22 along.

**Comment by nazmulhasan85** [comment]
@PedroBern Sounds good

Lemme have a look. If i can manage sometime I will definitely jump on it.

**Comment by PedroBern** [comment]
Started to work on this with #33 and adding a new branch, but I found some problems:
- In `RegisterMixin`, `SendSecondaryEmailActivationMixin` if the email is in use, it will still send a successful response.
- In `ResendActivationEmailMixin` if the user is already verified, it will still send a successful response.

The only way to fix it is by moving the logic of the exception out of the model, bringing it to the mixins. It will give a lot more work than expected. Not planning to work on this soon, because of it, I'm closing.
