### ISSUE TITLE
Add "me" query

### ISSUE THREAD

**Issue by pors** [PedroBern/django-graphql-auth#13]
It would be useful to have a "me" query where the client gets the details of the logged-in user (sending a JWT). The client doesn't have to store the ID in that case.

This could be done with something like this I think:

``` 
def resolve_me(self, info):
  user = info.context.user
  if user.is_anonymous:
    raise GraphQLError('Not logged in!')
```

What do you think?

**Comment by PedroBern** [comment]
It's a good idea! Could you send a PR?

**Comment by pors** [comment]
> It's a good idea! Could you send a PR?

I'd love to, but not sure how I can use the forked&cloned package in my django application. Maybe you can add a bit more detail in the contributing doc?

Just symlinking to it doesn't work, I get `RuntimeError: Model class myapp.graphql_auth.models.UserStatus doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`.

**Comment by PedroBern** [comment]
The easiest way is to fork and develop with the `testproject` folder or make a test-driven development with the `test` folder.

### Develop with the `testproject`

- Fork the repo
- Create a virtual env
- Install dependencies with `make dev-setup` and `pip install tox`
- Change the code inside the `graphql_auth` folder
- Run `make install-local v=0.3.4`, right now it is 0.3.4, but you should check it.
- `cd testproject` and work just like any django project, `./manage.py runserver`.

The drawback is you will need to reinstall every time you make a change in `graphql_auth`.

### Test Driven Development

- Fork the repo
- Create a virtual env
- Install dependencies with `make dev-setup` and `pip install tox`
- Change the code inside the `graphql_auth` folder
- Write tests inside the `tests` folder and run with the commands inside the `Makefile` from the root directory.

---

> can add a bit more detail in the contributing doc?

I will try to update it next week!

If you have further questions please let me know!

**Comment by pors** [comment]
Cool, thanks! I'll give it a try.

**Comment by pors** [comment]
I was thinking, maybe we should split `me` from `user` and `users`? In many use cases, the `user` and `users` query are not desired, unless the user is an admin maybe. Or is there another way to limit access to these queries?

**Comment by PedroBern** [comment]
It's a good point, maybe it's better to split, but would result in creating a completely new query? I'm not sure how to limit this access right now, but it would be the best option.

**Comment by pors** [comment]
Yeah I think a new query is needed then.

**Comment by PedroBern** [comment]
Code on! Make a new query then. Should we call it MeQuery?

**Comment by pors** [comment]
Yeah, will do. Are you OK with what I did so far? Django and Graphql are
relatively new for me, so feel free to provide more feedback.

Also, I think we should have a setting to be able to exclude specific
queries right? How would that work?

MeQuery sounds good to me!

**Comment by PedroBern** [comment]
Yes it's great, graphql is new for me too! This is my first project using it.

> I think we should have a setting to be able to exclude specific
queries right?
Please show me an exemple, I didn't understand what you mean

**Comment by pors** [comment]
> Please show me an example, I didn't understand what you mean

If we have a MeQuery and a UserQuery, in some use cases we don't want the UserQuery to be available. So we might need a setting for that?

**Comment by PedroBern** [comment]
I don't think so, because we can include only the query we would like to use in our root query

```python
class Query(UserQuery, MeQuery,  graphene.ObjectType):
    pass

# or
class Query(MeQuery,  graphene.ObjectType):
    pass

# or
class Query(UserQuery,  graphene.ObjectType):
    pass
```

**Comment by pors** [comment]
Ah yes of course!

**Comment by ulgens** [comment]
This can be moved to "Done" column on related project.
