### ISSUE TITLE
Example with custom user model

### ISSUE THREAD

**Issue by maxwaiyaki** [PedroBern/django-graphql-auth#18]
Is there an example with custom user model?

**Comment by PedroBern** [comment]
Currently not. Just make sure 2 points:

## Add the following to your model

Following the [Django custom user model](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#django.contrib.auth.models.CustomUser).

```python
USERNAME_FIELD = "<username_filed_name>" # e.g: "username", "email"
EMAIL_FIELD = "<email_field_name>" # e.g: "email", "primary_email"
```

## Add your model in the settings

See [here](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#substituting-a-custom-user-model) for more info.

```python
# settings

AUTH_USER_MODEL = 'myapp.MyUser'
```

**Comment by PedroBern** [comment]
Now the quickstart tutorial has a custom user model.
