### ISSUE TITLE
Owner invitation

### ISSUE THREAD

**Issue by grantmcconnaughey** [PedroBern/django-graphql-auth#2]
Hello,

I was recently invited to be an owner of this repo. Why is that? Did I post something related to this repo somewhere and forget about it?

**Comment by PedroBern** [comment]
Hello, I was recently adding collaborators, I probably did a mistake! Sorry!

**Comment by PedroBern** [comment]
Actually I remember now, I was looking for people who did contribute on graphene-django, saw you and I thought you might be interested. If you want let me know, I send the invitation again!

**Comment by PedroBern** [comment]
I'm deleting this because it's awkward.

Please contact me by email (you can see it on my profile) if you want to be a collaborator! Will be great!
