### ISSUE TITLE
ObtainJSONWebToken

### ISSUE THREAD

**Issue by sirb0rab0g1** [PedroBern/django-graphql-auth#38]
in documentation 
https://django-graphql-auth.readthedocs.io/en/latest/api/#obtainjsonwebtoken
it says "Not verified users can login by default. This can be changes on settings."
in which settings ? 
Problem: i can login by default but it is not verfied yet.
Question : where do i set verfied = True if after registration

**Comment by PedroBern** [comment]
> ... in which settings ?

[ALLOW_LOGIN_NOT_VERIFIED](https://django-graphql-auth.readthedocs.io/en/latest/settings/#allow_login_not_verified)

> Problem: i can login by default but it is not verfied yet.

Many apps allow users to login unverified, and restrict access to some actions. Sometimes it is quite useful if you want the user to register and start using it really fast. Then when the user tries to save something or do some specific action, you request for the verification (that was already send by email during registration).

> Question : where do i set verfied = True if after registration

During the registration, an email is sent to the user with a link. You should handle this link on your client, take the token from the link and send it to the [VerifyAccount](https://django-graphql-auth.readthedocs.io/en/latest/api/#verifyaccount) mutation. Then the user is verified. Did you complete the [quickstart](https://django-graphql-auth.readthedocs.io/en/latest/quickstart/)?

**Comment by sirb0rab0g1** [comment]
sorry about i was over thinking about i just read the docs btw. thanks for it.

additional question: 

how to update first_name / last_name in
'UPDATE_MUTATION_FIELDS': ['email', 'first_name', 'last_name']
from: 
first_name: 'x'
to:
first_name: 'y'

**Comment by sirb0rab0g1** [comment]
sorry about that i was overthinking about it.

additional question: how to update the first_name and last_name in customuser

users/models.py
class CustomUser(AbstractUser):
    USERNAME_FIELD = "username"   # e.g: "username", "email"
    EMAIL_FIELD = "email"         # e.g: "email", "primary_email"
    
settings.py
GRAPHQL_AUTH = {
    'LOGIN_ALLOWED_FIELDS': ['email', 'username'],
    'ALLOW_LOGIN_NOT_VERIFIED': False,
    'REGISTER_MUTATION_FIELDS': {
        "first_name": "String",
        "last_name": "String",
        "email": "String",
        "username": "String",
    },
    'UPDATE_MUTATION_FIELDS': ['first_name', 'last_name']
    # ...
}

ex: 
from: 
first_name: 'x'
to: 
first_name: 'y'

**Comment by sirb0rab0g1** [comment]
sorry it was clear not. i was overthinking abount it thanks @PedroBern
