### ISSUE TITLE
Email didnt validate upon registration when it's empty

### ISSUE THREAD

**Issue by sirb0rab0g1** [PedroBern/django-graphql-auth#39]
settings.py
GRAPHQL_AUTH = {
    'LOGIN_ALLOWED_FIELDS': ['email', 'username'],
    'ALLOW_LOGIN_NOT_VERIFIED': False,
    'REGISTER_MUTATION_FIELDS': ['email', 'username', 'first_name', 'last_name'],
    'UPDATE_MUTATION_FIELDS': ['first_name', 'last_name']
    # ...
}

#registration
`
mutation {
  register(
    email: "",
    username: "as",
    password1: "Pasmo.123",
    password2: "Pasmo.123",
    first_name: "wawex",
    last_name: "wawex"
  ) {
    success,
    errors,
    # token
  }
}
`
#response 
`{
  "data": {
    "register": {
      "success": true,
      "errors": null
    }
  }
}`

**Comment by PedroBern** [comment]
This is the expected behaivor with the default user model.

If you want to change this, create a custom user model with the following:

```python
email = models.EmailField(blank=False ...
```
