### ISSUE TITLE
Support For Logout?

### ISSUE THREAD

**Issue by jrozen-lab** [PedroBern/django-graphql-auth#4]
@PedroBern First of all, huge thanks for this repo and the great documentation. Very helpful indeed. I see that a lot of authentication methods have been implemented by a key one is missing. Once a user has been authenticated and logged in, how can that user then logout again?

I might be missing something fundamental however so any insight is appreciated!

**Comment by PedroBern** [comment]
@jrozen-lab thanks you are welcome! With JWT authentication, if not using refreshTokens, you simple delete the token in the frontend. With refreshTokens, you can use the revoke mutation to make it invalid, same as a logout.

See [this link](https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#logout) for further learning of jwt authentication on frontend.

**Comment by jrozen-lab** [comment]
@PedroBern Thanks for the explanation and links. Will read through it later today!

When using refreshTokens (and the revoke mutation to log someone out), does the revocation of the refresh token have an immediate effect or will the main token (not the refresh one) continue to live until expiry (and hence have logout only happen at that point in time)?

**Comment by PedroBern** [comment]
Yes, it take immediate effect for the refreshToken. But the regular token still works while it is not expired, so in your logout implementation on the frontend you should delete it when revoking the refreshToken. Once this token is deleted, you no longer have a token on the frontend, hence the user is logged out. Let me know if you have further questions.

**Comment by alejup21** [comment]
Hi, I try every way and nothig, Imagin that I have two tabs of the same web, and in one I logout, the other still have the token, And the problem is, that if a make a request, is still working. No matter what a do, Even if I revoke or refresh, the backend still validate that old token as good. Anyone can help with that?
