### ISSUE TITLE
last_login field does not updated

### ISSUE THREAD

**Issue by hellpirat** [PedroBern/django-graphql-auth#51]
# Description
I am using a token_auth mutation for login in my system.
When I check my User model in the database - last_login always is null.

# Steps to Reproduce
1. register new user via register mutation
2. confirm user via verify_account
3. get token via token_auth
4. check the last_login field in the database
## Expected behavior

I would like to see if the user gets a new token - last_login field updated to "now".

## What  happened

Nothing happened with last_login field

# Requirements
```
django==3.0.5
graphene-django==2.10.1
django-graphql-jwt==0.3.0
django-graphql-auth=0.3.10

```

**Comment by PedroBern** [comment]
Actually it's not a bug. Updating the last_login field is within the `django-graphql-jwt` scope. You should use the [token_issued](https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/signals.py#L3) signal. Probably you can do something like this:

```python
from graphql_jwt.signals import token_issued
from django.dispatch import receiver

from django.utils import timezone # if USE_TZ=True
# or import datetime if USE_TZ=False

@receiver(token_issued)
def update_last_login(sender, request, user):
    user.last_login = timezone.now()
    # or user.last_login = datetime.datetime.now()
    user.save(update_fields=['last_login'])
```
