### ISSUE TITLE
Graphql login does not return token

### ISSUE THREAD

**Issue by udemezue01** [PedroBern/django-graphql-auth#56]
When I try to log in and it does not return a JSON Token

mutation {
  tokenAuth(email: "johnzeus14@gmail.com", password: "oldskool123") {
    success,
    errors,
    unarchiving,
    token,
    refreshToken,
    unarchiving,
   
  }
}

{
  "data": {
    "tokenAuth": {
      "success": false,
      "errors": {
        "nonFieldErrors": [
          {
            "message": "Please, enter valid credentials.",
            "code": "invalid_credentials"
          }
        ]
      },
      "unarchiving": false,
      "token": null
    }
  }
}

**Comment by PedroBern** [comment]
Please use the issue template.

**Comment by Instrumedley** [comment]
I got the same issue

**Comment by panosangelopoulos** [comment]
Hi @udemezue01 and @Instrumedley ,

please give us more details regarding the issue and modify the body of the message.

- Are you able to authenticate your account using the Django authentication method?

**Comment by Instrumedley** [comment]
actually I solved this issue yesterday. In my situation it was a matter of this `django.contrib.auth.backends.ModelBackend` missing under AUTHENTICATION_BACKENDS on settings.py . Something that I think the instructions and quick guide tells you to do.

Now my issue is that I don't seem to be able to use protected queries correctly, so I posted a new question here
https://github.com/PedroBern/django-graphql-auth/issues/109 , since I'm a bit lost regarding the correct configs to use

**Comment by panosangelopoulos** [comment]
Thanks for your answer @Instrumedley !

I'm closing the issue.

**Comment by eyal-gor** [comment]
After requesting:
mutation {
  tokenAuth(email: "new_user", password: "supersecretpassword") {
    success,
    errors,
    unarchiving,
    token,
    refreshToken,
    unarchiving,
    user {
      id,
      username,
    }
  }
}

I'm getting:
{
  "data": {
    "tokenAuth": {
      "success": false,
      "errors": {
        "nonFieldErrors": [
          {
            "message": "Please, enter valid credentials.",
            "code": "invalid_credentials"
          }
        ]
      },
      "token": null,
      "refreshToken": null,
      "user": null
    }
  }
}

When I log in to the admin with these credentials everything works fine.

Help?

**Comment by eyal-gor** [comment]
I have a custom user class that looks like that:
class User(AbstractUser):
    objects = UserManager()  
    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    username = None
    email = models.EmailField("email address", blank=False, null=False, unique=True)
