### ISSUE TITLE
How to specify a custom domain for email verification link

### ISSUE THREAD

**Issue by abdellatifLabr** [PedroBern/django-graphql-auth#58]
This is a question on how to specify a custom domain for email verification link.
like in django settings we put:
DOMAIN = 'localhost:4200'

so I want to verify from the frontend.

**Comment by maxpeterson** [comment]
If you are referring to the email sent from the app then I think it uses the [Django sites framework](https://docs.djangoproject.com/en/3.0/ref/contrib/sites/), so you should be able to update the site `domain` in the django admin. You may need to restart your django server after changing the site object as it is cached.

**Comment by abdellatifLabr** [comment]
@maxpeterson Thank you!, You solved my problem
