### ISSUE TITLE
Can't exclude user node field "secondaryEmail" using USER_NODE_EXCLUDE_FIELDS

### ISSUE THREAD

**Issue by maxpeterson** [PedroBern/django-graphql-auth#60]
# Prerequisites

* [ ] Is it a bug?
* [ ] Is it a new feature?
* [x] Is it a a question?
* [x] Can you reproduce the problem?
* [ ] Are you running the latest version?
* [x] Did you check for similar issues?
* [x] Did you perform a cursory search?

# Description

I have tried using `USER_NODE_EXCLUDE_FIELDS` to exclude `secondaryEmail` however, since `secondaryEmail` is `resolved` it doen't seem possible to excluded it in this way.

Is there another mechanism to exclude these fields. My assumption is that I need to (re)create my own `UserNode` along with the `MeQuery` and `UserQuery`

**Comment by maxpeterson** [comment]
This is the second challenge I have faced that would be resolved by #57 - I promise that this is coincidental and it is not my intention to make a case for using mixins.

**Comment by PedroBern** [comment]
No, there isn't any other mechanism. And yes, probably you would need to recreate your one UserNode...

**Comment by maxpeterson** [comment]
Closing as the workaround is to create an alternative `UserNode` (or implement #57)
