### ISSUE TITLE
[Error!]: Invalid Token in verifyAccount Mutation

### ISSUE THREAD

**Issue by nietzscheson** [PedroBern/django-graphql-auth#64]
# Prerequisites

* [x] Is it a bug?
* [ ] Is it a new feature?
* [ ] Is it a a question?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [ ] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/PedroBern/django-graphql-auth/blob/master/CONTRIBUTING.md) guide.

# Description

VerifyAccount Mutation doesn't works

I've followed the [installation](https://django-graphql-auth.readthedocs.io/en/latest/installation/) instructions and checked the [Quickstart](https://github.com/PedroBern/django-graphql-auth/tree/master/quickstart) project to see if I've done anything wrong. The verifyAccount mutation fails. It throws me the error of: Invalid token

![Issue Video](https://media.giphy.com/media/QYRyI388dzSr7xgo0v/giphy.gif)

Oooh... the gif is too small... Here the process:

1. Register
<img width="1680" alt="register" src="https://user-images.githubusercontent.com/1699198/92314635-19825880-efa0-11ea-9481-78e464738e56.png">

2. VerifyToken
<img width="1680" alt="verifyToken" src="https://user-images.githubusercontent.com/1699198/92314648-374fbd80-efa0-11ea-99c4-9e8ae247b4e7.png">

3. VerifyAccount
<img width="1680" alt="verifyAccount" src="https://user-images.githubusercontent.com/1699198/92314651-3f0f6200-efa0-11ea-9f7a-f3aba0ecaad5.png">

**Comment by PedroBern** [comment]
Hi @nietzscheson is it the token from the email?

**Comment by lapillaga** [comment]
Hi I have the same problem. I have created my project with cookicutter by pydanny.

**Comment by lapillaga** [comment]
Sorry for my English
After a couple of hours I found our error.
The token that return the register query is not for verify the account. It's only for auth. You have to enter to console or test email managment (In my case a mailhog service). The email provide the right token for activate your account. 
![image](https://user-images.githubusercontent.com/42658241/93693195-16b85500-fac2-11ea-935f-56df9963da32.png)

![image](https://user-images.githubusercontent.com/42658241/93693193-0902cf80-fac2-11ea-866d-1ecff5716f0e.png)
As you can see, tokens are differents. Good luck.

**Comment by nietzscheson** [comment]
Ooooh, sorry for my last anwser! @lapillaga thanks... I also discovered it... I could not come to share it...
