### ISSUE TITLE
Create user without password by using set_unusable_password

### ISSUE THREAD

**Issue by joshuachinemezu** [PedroBern/django-graphql-auth#76]
# Prerequisites

* [ ] Is it a bug?
* [x] Is it a new feature?
* [x] Is it a a question?
* [ ] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [x] Did you perform a cursory search?

# Description

I want to be able to call the register mutation without having to pass the `password1` and `password2` args, thus using `set_unusable_password()` for creating a new account. Any recommendations on how to go about this?

**Comment by PedroBern** [comment]
Hi @joshuachinemezu it's not currently supported :(

**Comment by joshuachinemezu** [comment]
@PedroBern Okay great, thanks

**Comment by joshuachinemezu** [comment]
@PedroBern I'm currently working on this feature **Allow passwordless registration**, I will create a pull request once I'm done?

A boolean key `ALLOW_PASSWORDLESS_REGISTRATION` is added to the `GRAPHQL_AUTH` configuration in the settings file.

This feature will be a bedrock for [*Social authentication*](https://github.com/PedroBern/django-graphql-auth/projects/1#card-32459090) feature

_Keynotes_
- Allow user to register without password - use Django's `set_unusable_password()` to set the default password
- User can't log in until they've set a password for their account - Check if the user has a valid password using Django's `has_usable_password()`
- Allow user to set the password for their account (password1 and password2)

@PedroBern Let me know your take on having this feature. Thanks

**Comment by PedroBern** [comment]
@joshuachinemezu terrific PR I will release the changes now :D

**Comment by joshua-tap** [comment]
@PedroBern Thanks, it's a pleasure contributing to this amazing project. :)

**Comment by joshuachinemezu** [comment]
@PedroBern Thanks, it's a pleasure contributing to this amazing project. :)
