### ISSUE TITLE
Generate JWT by user

### ISSUE THREAD

**Issue by emilpriver** [PedroBern/django-graphql-auth#78]
# Prerequisites

* [ ] Is it a bug?
* [ ] Is it a new feature?
* [x ] Is it a a question?
* [ ] Can you reproduce the problem?
* [ ] Are you running the latest version?
* [ ] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/PedroBern/django-graphql-auth/blob/master/CONTRIBUTING.md) guide.

# Description
 Am I able to generate a JWT by adding a user to a function with this package? My goal is to be able to generate a JWT from a SSO sign in :D

**Comment by PedroBern** [comment]
Hi @emilpriver you can use the [django-grapphql-jwt](https://github.com/flavors/django-graphql-jwt) package to generate JWT tokens with graphql :)

**Comment by emilpriver** [comment]
> Hi @emilpriver you can use the [django-grapphql-jwt](https://github.com/flavors/django-graphql-jwt) package to generate JWT tokens with graphql :) 

Hello, yes. I meant if this package provide some kind of function in the code I can use to generate a jwt. Ex I parse a User instance and I get a JWT and refresh token in return ☺️
