### ISSUE TITLE
Set archived=True when user is registered

### ISSUE THREAD

**Issue by Cuda-Chen** [PedroBern/django-graphql-auth#92]
# Prerequisites

* [ ] Is it a bug?
* [ ] Is it a new feature?
* [x] Is it a a question?
* [ ] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/PedroBern/django-graphql-auth/blob/master/CONTRIBUTING.md) guide.

# Description
Hello everyone.
I would like to set `archived=True` in `UserStatus` model when user is registered successfully.
After tracing source code, I found this package uses Django signal to create corresponding user's status ([reference](https://github.com/PedroBern/django-graphql-auth/blob/master/graphql_auth/signals.py#L7)):
```python
@receiver(post_save, sender=django_settings.AUTH_USER_MODEL)
def create_user_status(sender, instance, created, **kwargs):
    if created:
        from .models import UserStatus

        UserStatus._default_manager.get_or_create(user=instance)
```

So I tried to use `defaults={'archived': True}` according to [Django official docs](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#get-or-create) but the `archived` field still set to `False` when created:
```python
@receiver(post_save, sender=django_settings.AUTH_USER_MODEL)
def create_user_status(sender, instance, created, **kwargs):
    if created:
        from .models import UserStatus

        UserStatus._default_manager.get_or_create(user=instance, defaults={'archived': True}) # I changed here.
```

In the end, is there any method to set `archived` to `True` when user is registered?

Thanks for your help!

**Comment by ulgens** [comment]
If you added that as another signal, it should be "create or update". Most probably, the existing signal is getting called first and yours just "get" the instance and do nothing. IMO, a better approach would be registering your signal to `UserStatus`'s post save.

**Comment by Cuda-Chen** [comment]
Hi @ulgens ,
Thanks for your help. Now I can set `archived=True` when each `UserStatus` instance is created.

As a memo, here are the procedures to solve this question:
1. Create a signal, for example `userstatus_created`, as follows:
```python
from django.dispatch import receiver, Signal
from graphql_auth.models import UserStatus

@receiver(post_save, sender=UserStatus)
def change_archived_to_true(sender, instance, created, **kwargs):
    if created:
        instance.archived = True
        instance.save()

userstatus_created = Signal(providing_args=["instance", "created"])
```
2. Remember to connect signals in `app.py` and `__init__.py` so that the signal will be connected when Django startups
(assume your Django app called `MyApp`):
```python
# app.py

from django.apps import AppConfig

class MyAppConfig(AppConfig):
    name = 'MyApp'
    verbose_name = 'MyApp config'

    def ready(self):
        import MyApp.signals
```
```python
# __init__.py

default_app_config = "MyApp.apps.MyAppConfig"
```
3. Run the server and you are on the go! Whenever you register, the user's `archived` in `UserStatus` will be always set to `True` .

**Comment by ulgens** [comment]
I'm closing the issue then :slightly_smiling_face:

**Comment by Cuda-Chen** [comment]
You can close this issue.
Thanks for your help!
